version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: stocksdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_USERNAME: postgres
      DB_PASSWORD: admin
      DB_NAME: stocksdb
      DB_DIALECT: postgres
      API_URL: http://localhost:3000
      PORT: 3000
    depends_on:
      - postgres
    ports:
      - "3000:3000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3001:80"

volumes:
  postgres_data:
